FROM alpine:3.20
RUN apk --no-cache add ca-certificates
COPY bin/api-gateway /api-gateway
COPY api/ /api/
EXPOSE 8080
ENTRYPOINT ["/api-gateway", "-db", "postgres://postgres:postgres@gpu-telemetry-postgresql:5432/telemetry?sslmode=disable"]
