FROM golang:1.22-alpine AS build
WORKDIR /app
COPY go.mod go.sum ./
RUN go mod download
COPY . .
RUN CGO_ENABLED=0 GOOS=linux go build -ldflags="-s -w" -o /bin/mq ./cmd/mq

FROM alpine:3.20
RUN apk --no-cache add ca-certificates
COPY --from=build /bin/mq /mq
ENTRYPOINT ["/mq"]
