FROM alpine:3.20
RUN apk --no-cache add ca-certificates
COPY bin/collector /collector
ENTRYPOINT ["/collector", "-mq", "gpu-telemetry-mq:50051", "-db", "postgres://postgres:postgres@gpu-telemetry-postgresql:5432/telemetry?sslmode=disable"]
