FROM golang:1.22-alpine AS build
WORKDIR /app
COPY . .
RUN go build -o /bin/streamer ./cmd/streamer

FROM alpine:3.20
COPY --from=build /bin/streamer /streamer
RUN mkdir -p /data
COPY data/ /data/
ENTRYPOINT ["/streamer", "-csv", "/data/dcgm_metrics_20250718_134233.csv"]
