global:
  imagePrefix: localhost
streamer:
  enabled: true
collector:
  enabled: true
mq:
  enabled: true
api-gateway:
  enabled: true
  service:
    type: NodePort
    nodePort: 30080
postgresql:
  enabled: true
