apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "gpu-telemetry.fullname" . }}-collector
  namespace: {{ .Release.Namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: collector
  template:
    metadata:
      labels:
        app.kubernetes.io/name: collector
    spec:
      containers:
      - name: collector
        image: "{{ .Values.global.imagePrefix }}/collector:latest"
        imagePullPolicy: IfNotPresent
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "gpu-telemetry.fullname" . }}-collector
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    app.kubernetes.io/name: collector
  ports:
  - port: 50051
    targetPort: 50051
