// Code generated by protoc-gen-go. DO NOT EDIT.
package pb

type Message struct {
	Data                []byte `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	TimestampUnixNano   int64  `protobuf:"varint,2,opt,name=timestamp_unix_nano,json=timestampUnixNano,proto3" json:"timestamp_unix_nano,omitempty"`
}

type SubscribeRequest struct {
	Topic         string `protobuf:"bytes,1,opt,name=topic,proto3" json:"topic,omitempty"`
	ConsumerGroup string `protobuf:"bytes,2,opt,name=consumer_group,json=consumerGroup,proto3" json:"consumer_group,omitempty"`
}

type PublishResponse struct {
	Ok bool `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
}

type HealthRequest struct {
}

type HealthResponse struct {
	Ready bool `protobuf:"varint,1,opt,name=ready,proto3" json:"ready,omitempty"`
}
