// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
)

type MessageQueueClient interface {
	Publish(ctx context.Context, opts ...grpc.CallOption) (MessageQueue_PublishClient, error)
	Subscribe(ctx context.Context, in *SubscribeRequest, opts ...grpc.CallOption) (MessageQueue_SubscribeClient, error)
	Health(ctx context.Context, in *HealthRequest, opts ...grpc.CallOption) (*HealthResponse, error)
}

type messageQueueClient struct {
	cc grpc.ClientConnInterface
}

func NewMessageQueueClient(cc grpc.ClientConnInterface) MessageQueueClient {
	return &messageQueueClient{cc}
}

type MessageQueue_PublishClient interface {
	Send(*Message) error
	CloseAndRecv() (*PublishResponse, error)
	grpc.ClientStream
}

type MessageQueue_SubscribeClient interface {
	Recv() (*Message, error)
	grpc.ClientStream
}

func (c *messageQueueClient) Publish(ctx context.Context, opts ...grpc.CallOption) (MessageQueue_PublishClient, error) {
	stream, err := c.cc.NewStream(ctx, nil, "/pb.MessageQueue/Publish", opts...)
	if err != nil {
		return nil, err
	}
	x := &messageQueuePublishClient{stream}
	return x, nil
}

type messageQueuePublishClient struct {
	grpc.ClientStream
}

func (x *messageQueuePublishClient) Send(m *Message) error {
	return x.ClientStream.SendMsg(m)
}

func (x *messageQueuePublishClient) CloseAndRecv() (*PublishResponse, error) {
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	m := new(PublishResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *messageQueueClient) Subscribe(ctx context.Context, in *SubscribeRequest, opts ...grpc.CallOption) (MessageQueue_SubscribeClient, error) {
	stream, err := c.cc.NewStream(ctx, nil, "/pb.MessageQueue/Subscribe", opts...)
	if err != nil {
		return nil, err
	}
	x := &messageQueueSubscribeClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type messageQueueSubscribeClient struct {
	grpc.ClientStream
}

func (x *messageQueueSubscribeClient) Recv() (*Message, error) {
	m := new(Message)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *messageQueueClient) Health(ctx context.Context, in *HealthRequest, opts ...grpc.CallOption) (*HealthResponse, error) {
	out := new(HealthResponse)
	err := c.cc.Invoke(ctx, "/pb.MessageQueue/Health", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

type MessageQueueServer interface {
	Publish(MessageQueue_PublishServer) error
	Subscribe(*SubscribeRequest, MessageQueue_SubscribeServer) error
	Health(context.Context, *HealthRequest) (*HealthResponse, error)
}

type MessageQueue_PublishServer interface {
	SendAndClose(*PublishResponse) error
	Recv() (*Message, error)
	grpc.ServerStream
}

type MessageQueue_SubscribeServer interface {
	Send(*Message) error
	grpc.ServerStream
}
